version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - "3000:3000"

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      APP_PORT: 3000
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: knowledge
      POSTGRES_DB: knowledge_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
